idf_component_register(
    SRCS 
        "adc.c"
        "decode_image.c"
        "font5x7.c"
        "imu.c"
        "joystick.c"
        "lcd.c"
        "led.c"
        "metrics.c"
        "pretty_effect.c"
        "setup.c"
        "speaker.c"
        "tjpgd.c"
        "trans_main.c"
        "transmit_data.c"
        "uart_control.c"
    INCLUDE_DIRS "../include"
    EMBED_FILES 
        "images/frame1.jpg"
        "images/frame2.jpg"
        "images/frame3.jpg"
        "images/frame4.jpg"
        "images/frame5.jpg"
        "images/frame6.jpg"
        "images/frame7.jpg"
        "images/frame8.jpg"
        "images/frame9.jpg"
        "images/frame10.jpg"
        "images/frame11.jpg"
        "images/frame12.jpg"
        "images/frame13.jpg"
        "images/frame14.jpg"
        "images/frame15.jpg"
        "images/left.jpg"
        "images/leftright.jpg"
        "images/linkedin.jpg"
        "images/github.jpg"
        "images/blankfirstpage.jpg"
        "images/secondpagedata.jpg"
        "images/autofirst.jpg"
        "images/autofirststop.jpg"
        "images/imufirst.jpg"
)
